flaskapp/users/forms.py
from flask_wtf import FlaskForm
from flask import current_app
from flask_login import current_user
from wtforms.validators import DataRequired, Email, EqualTo, Length, ValidationError
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField
from flask_wtf.file import FileField, FileAllowed
from flaskapp.models import User, ProviderType, Provider, Role


class UserRegistrationForm(FlaskForm):
    first_name = StringField('First Name', validators=[
        DataRequired(), Length(min=2, max=155)])
    last_name = StringField('Last Name', validators=[
        DataRequired(), Length(min=2, max=155)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    # def validate_field(self, field):
    #    if True:
    #        return ValidationError('Validation Message')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                'This email is taken. Please choose a different one!')


class UserLoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('login')


class UserUpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    picture = FileField('Update profile picture', validators=[
                        FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    'This username is taken. Please Choose a different one')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    'This email is taken. Please choose a different one')


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()

        if user is None:
            raise ValidationError(
                'There is no account with that email. You need to register')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Old Password', validators=[DataRequired()])
    confirm_password = PasswordField('New Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Password Reset')


class ProviderTypeForm(FlaskForm):
    name = StringField('Provider Type', validators=[
        DataRequired(), Length(min=2, max=155)])
    submit = SubmitField('Create')

    def validate_name(self, name):
        provider_type = ProviderType.query.filter_by(name=name.data).first()
        if provider_type:
            raise ValidationError(
                "The provider type is Already taken, Please chose a different one!")


class ProviderForm(FlaskForm):
    def __init__(self, *args, **kwargs):
        super(ProviderForm, self).__init__(*args, **kwargs)
        with current_app.app_context():
            providers = Provider.query.all()
            provider_types = ProviderType.query.all()
            empty_choice = [("", "-------------")]
            choices = empty_choice + [(str(provider.id), provider.name)
                                      for provider in providers]
            provider_type_choices = empty_choice + [
                (provider_type.id, provider_type.name) for provider_type in provider_types]
            self.provider_type.choices = provider_type_choices
            self.provider.choices = choices

    name = StringField('Provider Name', validators=[
        DataRequired(), Length(min=2, max=155)])
    provider = SelectField("Select provider")
    provider_type = SelectField("Select provider type")
    submit = SubmitField('Create')

    def validate_name(self, name):
        provider = Provider.query.filter_by(
            name=name.data, parent_id=self.provider.data, provider_type_id=self.provider_type.data).first()
        if provider:
            raise ValidationError(
                "The provider name is Already taken, Please chose a different one!")


class RoleForm(FlaskForm):
    name = StringField('Role', validators=[
        DataRequired(), Length(min=2, max=155)])
    description = TextAreaField('Description', validators=[
                                Length(max=255)], render_kw={"rows": 5})
    submit = SubmitField('Create')

    def validate_name(self, name):
        role = Role.query.filter_by(name=name.data).first()
        if role:
            raise ValidationError(
                "This Role Exist, Please chose a different one!")


class UserBioForm(FlaskForm):
    biography = TextAreaField('Biography', validators=[
        Length(max=255)], render_kw={"rows": 5})
    image = FileField('Update Bio Image', validators=[
        FileAllowed(['jpg', 'png'])])


class LearnerPersornalDetailsForm(FlaskForm):
    title = StringField('Title', validators=[
        DataRequired(), Length(min=2, max=20)])
    dob = StringField('Date ', validators=[
        DataRequired(), Length(min=2, max=155)])
    gender = SelectField("Select Gender", choices=[
        "Male", "Female", "Other"
    ])
    
class LearnerContactForm(FlaskForm):
    cellphone = StringField('Contact', validators=[
        DataRequired(), Length(min=2, max=10)])

flaskapp/users/views.py
from flask import render_template, redirect, flash, request, url_for, Blueprint
from flaskapp.users.forms import (
    UserRegistrationForm,
    UserLoginForm, UserUpdateAccountForm,
    RequestResetForm, ResetPasswordForm,
    ProviderForm, ProviderTypeForm,
    RoleForm
)
from flaskapp.models import User, Provider, ProviderType, Role
from werkzeug.security import generate_password_hash, check_password_hash
from flaskapp.models import db
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp.users.utils import save_picture, send_reset_email
from flaskapp.decorators import role_required

auth = Blueprint('auth', __name__)


# Create Registration route
@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = UserRegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User(first_name=form.first_name.data, last_name=form.last_name.data,
                    email=form.email.data, password=generate_password_hash(form.password.data, method='pbkdf2:sha256'))
        db.session.add(user)
        db.session.commit()
        flash(f'You are successfully registered, you can now login', 'success')
        return redirect(url_for('auth.login'))
    return render_template('users/register.html', title='Register', form=form, user=current_user)


# Create login route
@auth.route('/login', methods=['POST', 'GET'])
def login():
    form = UserLoginForm()
    if current_user.is_authenticated:
        return redirect('home')
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                if user.has_role("Admin"):
                    return redirect(url_for('auth.admin'))
                return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash('Your username or password does not match!',
                  'error')
    return render_template('users/login.html', title='Login', form=form, user=current_user)


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UserUpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated successifully!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for(
        'static', filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html', title='Account', image_file=image_file, form=form, user=current_user)

 # Create a route for every user posts


@auth.route("/admin", methods=["GET"])
@login_required
@role_required('Admin')
def admin():
    return render_template("admin/index.html", user=current_user)


@auth.route("/providers", methods=["GET"])
@login_required
@role_required('Admin')
def providers():
    providers = Provider.query.filter(Provider.parent_id == 0).all()
    return render_template("admin/providers.html", user=current_user, providers=providers)


@auth.route("/provider-types", methods=["GET"])
@login_required
@role_required('Admin')
def provider_types():
    provider_types = ProviderType.query.all()
    return render_template("admin/provider_types.html", user=current_user, provider_types=provider_types)


# Roles
@auth.route("/roles", methods=["GET"])
@login_required
@role_required('Admin')
def roles():
    roles = Role.query.all()
    return render_template("admin/roles.html", user=current_user, roles=roles)


# Create Provider route
@auth.route("/providers/create", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def create_provider():
    form = ProviderForm()
    if request.method == "POST" and form.validate_on_submit():
        if form.provider.data == "":
            provider = Provider(
                name=form.name.data,
                provider_type_id=int(form.provider_type.data)
            )
        else:
            provider = Provider(
                name=form.name.data,
                parent_id=form.provider.data,
                provider_type_id=form.provider_type.data
            )
        db.session.add(provider)
        db.session.commit()
        flash("Provider is successfully created!", "success")
        return redirect(url_for('auth.providers'))
    return render_template("admin/create_provider.html", form=form, user=current_user)

# Edit Provider Route


@auth.route("/providers/<int:id>/edit", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def edit_provider(id):
    provider = Provider.query.get_or_404(id)
    form = ProviderForm(obj=provider)
    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(provider)
        db.session.commit()
        flash("Provider Updated Successfully!", "success")
        return redirect(url_for("auth.providers"))
    return render_template("admin/edit_provider.html", form=form, user=current_user)

# Delete Provider


@auth.route("/providers/<int:id>/delete", methods=["POST"])
@login_required
@role_required('Admin')
def delete_provider(id):
    provider = Provider.query.get_or_404(id)
    db.session.delete(provider)
    db.session.commit()
    flash('Provider deleted successfully!', 'success')
    return redirect(url_for('auth.providers'))

# List all users


@auth.route("/", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def users():
    users = User.query.all()
    return render_template("admin/users.html", user=current_user, users=users)

# user detail


@auth.route("/<int:id>", methods=["GET", "POST"])
@login_required
# @role_required('Admin')
def user_detail(id):
    obj = User.query.get_or_404(id)
    roles = Role.query.all()
    return render_template("admin/user_detail.html", user=current_user, users=users, obj=obj, roles=roles)


@auth.route("/provider-type/create", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def create_provider_type():
    form = ProviderTypeForm()
    if request.method == "POST":
        # print(request.form.get("provider"))
        if form.validate_on_submit():
            provider_type = ProviderType(
                name=form.name.data,
            )
            db.session.add(provider_type)
            db.session.commit()
            flash("Provider type is successfully created!", "success")
            return redirect(url_for('auth.provider_types'))
    return render_template("admin/create_provider_type.html", form=form, user=current_user)


# edit Provider Type
@auth.route("/provider-types/<int:id>/edit", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def edit_provider_type(id):
    provider_type = ProviderType.query.get_or_404(id)
    form = ProviderTypeForm(obj=provider_type)
    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(provider_type)
        db.session.commit()
        flash("Provider Type Updated Successfully!", "success")
        return redirect(url_for("auth.provider_types"))
    return render_template("admin/edit_provider_type.html", form=form, user=current_user)


# Delete provider Type
@auth.route("/provider-types/<int:id>/delete", methods=["POST"])
@login_required
@role_required('Admin')
def delete_provider_type(id):
    provider_type = ProviderType.query.get_or_404(id)
    db.session.delete(provider_type)
    db.session.commit()
    flash('Provider Type deleted successfully!', 'success')
    return redirect(url_for('auth.provider_types'))


# User Dashboard
@auth.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return render_template("users/dashboard.html", title="Dashboard", user=current_user)

# new role


@auth.route("/roles/create", methods=["GET", "POST"])
@login_required
# @role_required('Admin')
def create_role():
    form = RoleForm()
    if request.method == "POST" and form.validate_on_submit():
        role = Role(
            name=form.name.data,
            description=form.description.data
        )
        db.session.add(role)
        db.session.commit()
        flash("Role added successfully", "success")
        return redirect(url_for('auth.roles'))
    return render_template("admin/create_role.html", user=current_user, form=form)

# assign user roles


@auth.route("/<int:id>/roles", methods=["POST"])
@login_required
# @role_required('Admin')
def assign_roles(id):
    user = User.query.get_or_404(id)
    roles = request.form.getlist('roles')
    print(roles)
    user.roles = []

    # Assign new roles to the user
    for role_id in roles:
        role = Role.query.get(role_id)
        if role:
            user.roles.append(role)
    db.session.commit()
    return redirect(url_for('auth.user_detail', id=user.id))


@auth.route('/user/<string:username>/')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template('user_posts.html', posts=posts, user=user)


# create a route for password request
@auth.route('/password_reset', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

flaskapp/templates/users/dashboard.html
{% extends 'base.html' %} {% block title %} {{ title }} {% endblock title %}
<!--block content -->
{% block content %}
<div class="text-gray-700">Dashboard</div>
{% endblock content %}

flaskapp/templates/users/login.html
{% extends 'base.html' %} {% block title %} {{ title }} {% endblock title %}
<!--block content -->
{% block content %}
<div class="max-w-md mx-auto mt-12 text-gray-500 mb-6">
  <form method="post" action="">
    <fieldset class="container">
      <legend class="text-2xl text-center font-semi-bold">Login</legend>
      {{ form.hidden_tag() }}
      <div class="mb-6">
        {{ form.email.label(class= 'block mb-2 text-sm font-medium text-gray-900
        dark:text-white') }}
        <div class="input-group input-group-sm">
          {% if form.email.errors %} {{ form.email(class= 'bg-red-50 border
          border-red-500 text-red-900 placeholder-red-700 text-sm rounded-lg
          focus:ring-red-500 dark:bg-gray-700 focus:border-red-500 block w-full
          p-2.5 dark:text-red-500 dark:placeholder-red-500
          dark:border-red-500')}} {% for error in form.email.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.email(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }} {% endif %}
        </div>
      </div>
      <div class="mb-6">
        {{ form.password.label(class= 'block mb-2 text-sm font-medium
        text-gray-900 dark:text-white') }}
        <div class="w-full">
          {% if form.password.errors %} {{ form.password(class= 'bg-red-50
          border border-red-500 text-red-900 placeholder-red-700 text-sm
          rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500
          block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500
          dark:border-red-500')}} {% for error in form.password.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.password(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }} {% endif %}
        </div>
      </div>
      <div class="my-3 flex space-x-2">
        {{ form.remember(class= 'checkbox mt-2') }}
        <!---->
        {{ form.remember.label(class= 'label') }}
      </div>
      <div class="form-group">
        {{ form.submit(class= 'btn btn-outline btn-accent w-full') }}
        <small class="text-muted ml-2">
          <a href="{{ url_for('auth.reset_request')}}">Forgot password</a>
        </small>
      </div>
    </fieldset>
  </form>
  <div class="border-top">
    <p class="text-muted">
      Need an account?
      <a class="mr-4" href="{{url_for('auth.register')}}">Sign Up</a>
    </p>
  </div>
</div>
{% endblock content %}

flaskapp/templates/users/register.html
{% extends 'base.html' %} {% block title %} {{ title }} {% endblock title %}

<!---->
{% block content %}
<div class="max-w-md mx-auto mt-12 text-gray-500 mb-6">
  <form method="post" action="">
    <fieldset class="container">
      <legend class="border-bottom text-center mb-3">Join today</legend>
      {{ form.hidden_tag() }}
      <div class="form-control">
        {{ form.first_name.label(class= 'block mb-2 text-sm font-medium
        text-gray-900 dark:text-white') }}
        <div class="">
          {% if form.first_name.errors %} {{ form.first_name(class= 'bg-red-50
          border border-red-500 text-red-900 placeholder-red-700 text-sm
          rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500
          block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500
          dark:border-red-500') }} {% for error in form.first_name.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.first_name(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }}
          <!---->
          {% endif %}
        </div>
      </div>
      <div class="form-control">
        {{ form.first_name.label(class= 'block mb-2 text-sm font-medium
        text-gray-900 dark:text-white') }}
        <div class="">
          {% if form.last_name.errors %}
          <!---->
          {{ form.last_name(class= 'bg-red-50 border border-red-500 text-red-900
          placeholder-red-700 text-sm rounded-lg focus:ring-red-500
          dark:bg-gray-700 focus:border-red-500 block w-full p-2.5
          dark:text-red-500 dark:placeholder-red-500 dark:border-red-500') }}
          <!---->
          {% for error in form.last_name.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.last_name(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }}
          <!---->
          {% endif %}
        </div>
      </div>
      <div class="form-control">
        {{ form.email.label(class= 'block mb-2 text-sm font-medium text-gray-900
        dark:text-white') }}
        <div class="input-group input-group-sm">
          {% if form.email.errors %} {{ form.email(class= 'bg-red-50 border
          border-red-500 text-red-900 placeholder-red-700 text-sm rounded-lg
          focus:ring-red-500 dark:bg-gray-700 focus:border-red-500 block w-full
          p-2.5 dark:text-red-500 dark:placeholder-red-500 dark:border-red-500
          ') }} {% for error in form.username.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.email(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }}
          <!---->
          {% endif %}
        </div>
      </div>
      <div class="form-control">
        {{ form.password.label(class= 'block mb-2 text-sm font-medium
        text-gray-900 dark:text-white') }}
        <div class="input-group input-group-sm">
          {% if form.password.errors %} {{ form.password(class= 'bg-red-50
          border border-red-500 text-red-900 placeholder-red-700 text-sm
          rounded-lg focus:ring-red-500 dark:bg-gray-700 focus:border-red-500
          block w-full p-2.5 dark:text-red-500 dark:placeholder-red-500
          dark:border-red-500 ') }} {% for error in form.password.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %} {{ form.password(class= 'bg-gray-50 border
          border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }}
          <!---->
          {% endif %}
        </div>
      </div>
      <div class="mb-3 form-control">
        {{ form.confirm_password.label(class= 'block mb-2 text-sm font-medium
        text-gray-900 dark:text-white') }}
        <div class="input-group input-group-sm">
          {% if form.confirm_password.errors %} {{ form.confirm_password(class=
          'bg-red-50 border border-red-500 text-red-900 placeholder-red-700
          text-sm rounded-lg focus:ring-red-500 dark:bg-gray-700
          focus:border-red-500 block w-full p-2.5 dark:text-red-500
          dark:placeholder-red-500 dark:border-red-500') }} {% for error in
          form.confirm_password.errors %}
          <div class="invalid-feedback">
            <span>{{ error }}</span>
          </div>
          {% endfor %} {% else %}
          <!---->
          {{ form.confirm_password(class= 'bg-gray-50 border border-gray-300
          text-gray-900 text-sm rounded-lg focus:ring-blue-500
          focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
          dark:focus:ring-blue-500 dark:focus:border-blue-500') }} {% endif %}
        </div>
      </div>
      <div class="mb-3 form-group">
        {{ form.submit(class= 'btn btn-outline btn-accent w-full') }}
      </div>
    </fieldset>
  </form>
  <div class="border-top">
    <small class="text-muted">Already have an Account? </small>
    <a class="ml-4" href="{{url_for('auth.login')}}">Login</a>
  </div>
</div>
{% endblock content %}

flaskapp/templates/users/reset_request.html
{% extends 'base.html' %} {% block title %} {{ title }} {% endblock title %} {%
block content %}
<form class="mt-12 p-10 mx-auto max-w-lg shadow" method="post" action="">
  <fieldset class="container">
    <legend class="text-center text-gray-500">Password Reset</legend>
    {{ form.hidden_tag() }}
    <div class="form-control">
      {{ form.email.label(class= 'block mb-2 text-sm font-medium text-gray-900
      dark:text-white') }}
      <div class="input-group input-group-sm">
        {% if form.email.errors %}
        <!---->
        {{ form.email(class= 'bg-red-50 border border-red-500 text-red-900
        placeholder-red-700 text-sm rounded-lg focus:ring-red-500
        dark:bg-gray-700 focus:border-red-500 block w-full p-2.5
        dark:text-red-500 dark:placeholder-red-500 dark:border-red-500')}}
        <!---->
        {% for error in form.email.errors %}
        <div class="invalid-feedback">
          <span class="mt-2 text-sm text-red-600 dark:text-red-500"
            >{{ error }}</span
          >
        </div>
        {% endfor %} {% else %} {{ form.email(class= 'bg-gray-50 border
        border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500
        focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
        dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
        dark:focus:ring-blue-500 dark:focus:border-blue-500') }} {% endif %}
      </div>
    </div>
    <div class="my-3 form-group">
      {{ form.submit(class= 'btn btn-outline btn-accent w-full') }}
    </div>
  </fieldset>
</form>
{% endblock content %}

flaskapp/templates/users/reset_token.html
{% extends 'base.html' %} {% block title %} {{ title }} {% endblock title %} {%
block content %}
<form method="post" action="">
  <fieldset class="container">
    <legend class="border-bottom text-center mb-3">Password Reset</legend>
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.password.label(class= 'form-label') }}
      <div class="input-group input-group-sm">
        {% if form.password.errors %} {{ form.password(class= 'form-control
        is-invalid')}} {% for error in form.password.errors %}
        <div class="invalid-feedback">
          <span>{{ error }}</span>
        </div>
        {% endfor %} {% else %} {{ form.password(class= 'form-control') }} {%
        endif %}
      </div>
    </div>
    <div class="form-group">
      {{ form.confirm_password.label(class= 'form-label') }}
      <div class="input-group input-group-sm">
        {% if form.confirm_password.errors %} {{ form.confirm_password(class=
        'form-control is-invalid')}} {% for error in
        form.confirm_password.errors %}
        <div class="invalid-feedback">
          <span>{{ error }}</span>
        </div>
        {% endfor %} {% else %} {{ form.confirm_password(class= 'form-control')
        }} {% endif %}
      </div>
    </div>
    <div class="mb-3 form-group">
      {{ form.submit(class= 'btn btn-outline-secondary btn-sm') }}
    </div>
  </fieldset>
</form>
{% endblock content %}