flaskapp/users/views.py
from flask import render_template, redirect, flash, request, url_for, Blueprint
from flaskapp.users.forms import (
    UserRegistrationForm,
    UserLoginForm, UserUpdateAccountForm,
    RequestResetForm, ResetPasswordForm,
    ProviderForm, ProviderTypeForm,
    RoleForm
)
from flaskapp.models import User, Provider, ProviderType, Role
from werkzeug.security import generate_password_hash, check_password_hash
from flaskapp.models import db
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp.users.utils import save_picture, send_reset_email
from flaskapp.decorators import role_required

auth = Blueprint('auth', __name__)


# Create Registration route
@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = UserRegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User(first_name=form.first_name.data, last_name=form.last_name.data,
                    email=form.email.data, password=generate_password_hash(form.password.data, method='pbkdf2:sha256'))
        db.session.add(user)
        db.session.commit()
        flash(f'You are successfully registered, you can now login', 'success')
        return redirect(url_for('auth.login'))
    return render_template('users/register.html', title='Register', form=form, user=current_user)


# Create login route
@auth.route('/login', methods=['POST', 'GET'])
def login():
    form = UserLoginForm()
    if current_user.is_authenticated:
        return redirect('home')
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                if user.has_role("Admin"):
                    return redirect(url_for('auth.admin'))
                return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash('Your username or password does not match!',
                  'error')
    return render_template('users/login.html', title='Login', form=form, user=current_user)


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UserUpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated successifully!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for(
        'static', filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html', title='Account', image_file=image_file, form=form, user=current_user)

 # Create a route for every user posts


@auth.route("/admin", methods=["GET"])
@login_required
@role_required('Admin')
def admin():
    return render_template("admin/index.html", user=current_user)


@auth.route("/providers", methods=["GET"])
@login_required
@role_required('Admin')
def providers():
    providers = Provider.query.filter(Provider.parent_id == 0).all()
    return render_template("admin/providers.html", user=current_user, providers=providers)


@auth.route("/provider-types", methods=["GET"])
@login_required
@role_required('Admin')
def provider_types():
    provider_types = ProviderType.query.all()
    return render_template("admin/provider_types.html", user=current_user, provider_types=provider_types)


# Roles
@auth.route("/roles", methods=["GET"])
@login_required
@role_required('Admin')
def roles():
    roles = Role.query.all()
    return render_template("admin/roles.html", user=current_user, roles=roles)


# Create Provider route
@auth.route("/providers/create", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def create_provider():
    form = ProviderForm()
    if request.method == "POST" and form.validate_on_submit():
        if form.provider.data == "":
            provider = Provider(
                name=form.name.data,
                provider_type_id=int(form.provider_type.data)
            )
        else:
            provider = Provider(
                name=form.name.data,
                parent_id=form.provider.data,
                provider_type_id=form.provider_type.data
            )
        db.session.add(provider)
        db.session.commit()
        flash("Provider is successfully created!", "success")
        return redirect(url_for('auth.providers'))
    return render_template("admin/create_provider.html", form=form, user=current_user)

# Edit Provider Route


@auth.route("/providers/<int:id>/edit", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def edit_provider(id):
    provider = Provider.query.get_or_404(id)
    form = ProviderForm(obj=provider)
    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(provider)
        db.session.commit()
        flash("Provider Updated Successfully!", "success")
        return redirect(url_for("auth.providers"))
    return render_template("admin/edit_provider.html", form=form, user=current_user)

# Delete Provider


@auth.route("/providers/<int:id>/delete", methods=["POST"])
@login_required
@role_required('Admin')
def delete_provider(id):
    provider = Provider.query.get_or_404(id)
    db.session.delete(provider)
    db.session.commit()
    flash('Provider deleted successfully!', 'success')
    return redirect(url_for('auth.providers'))

# List all users


@auth.route("/", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def users():
    users = User.query.all()
    return render_template("admin/users.html", user=current_user, users=users)

# user detail


@auth.route("/<int:id>", methods=["GET", "POST"])
@login_required
# @role_required('Admin')
def user_detail(id):
    obj = User.query.get_or_404(id)
    roles = Role.query.all()
    return render_template("admin/user_detail.html", user=current_user, users=users, obj=obj, roles=roles)


@auth.route("/provider-type/create", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def create_provider_type():
    form = ProviderTypeForm()
    if request.method == "POST":
        # print(request.form.get("provider"))
        if form.validate_on_submit():
            provider_type = ProviderType(
                name=form.name.data,
            )
            db.session.add(provider_type)
            db.session.commit()
            flash("Provider type is successfully created!", "success")
            return redirect(url_for('auth.provider_types'))
    return render_template("admin/create_provider_type.html", form=form, user=current_user)


# edit Provider Type
@auth.route("/provider-types/<int:id>/edit", methods=["GET", "POST"])
@login_required
@role_required('Admin')
def edit_provider_type(id):
    provider_type = ProviderType.query.get_or_404(id)
    form = ProviderTypeForm(obj=provider_type)
    if request.method == "POST" and form.validate_on_submit():
        form.populate_obj(provider_type)
        db.session.commit()
        flash("Provider Type Updated Successfully!", "success")
        return redirect(url_for("auth.provider_types"))
    return render_template("admin/edit_provider_type.html", form=form, user=current_user)


# Delete provider Type
@auth.route("/provider-types/<int:id>/delete", methods=["POST"])
@login_required
@role_required('Admin')
def delete_provider_type(id):
    provider_type = ProviderType.query.get_or_404(id)
    db.session.delete(provider_type)
    db.session.commit()
    flash('Provider Type deleted successfully!', 'success')
    return redirect(url_for('auth.provider_types'))


# User Dashboard
@auth.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return render_template("users/dashboard.html", title="Dashboard", user=current_user)

# new role


@auth.route("/roles/create", methods=["GET", "POST"])
@login_required
# @role_required('Admin')
def create_role():
    form = RoleForm()
    if request.method == "POST" and form.validate_on_submit():
        role = Role(
            name=form.name.data,
            description=form.description.data
        )
        db.session.add(role)
        db.session.commit()
        flash("Role added successfully", "success")
        return redirect(url_for('auth.roles'))
    return render_template("admin/create_role.html", user=current_user, form=form)

# assign user roles


@auth.route("/<int:id>/roles", methods=["POST"])
@login_required
# @role_required('Admin')
def assign_roles(id):
    user = User.query.get_or_404(id)
    roles = request.form.getlist('roles')
    print(roles)
    user.roles = []

    # Assign new roles to the user
    for role_id in roles:
        role = Role.query.get(role_id)
        if role:
            user.roles.append(role)
    db.session.commit()
    return redirect(url_for('auth.user_detail', id=user.id))


@auth.route('/user/<string:username>/')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template('user_posts.html', posts=posts, user=user)


# create a route for password request
@auth.route('/password_reset', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

flaskapp/views.py
from flask import Blueprint, render_template, request, flash, url_for
from flask_login import login_required, current_user

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def home():
    return render_template("landing.html", user=current_user)


@views.route('/creator-courses-list', methods=['GET', 'POST'])
def creator_courses_list():
    return render_template("creator-courses-list.html", user=current_user)

flaskapp/templates/add_course.html
{% extends "creatorlayout.html" %}
{% block title %} Create Course {% endblock %}

{%block content%}

<div class="p-16">
    <div class="text-gray-500">
    <h1 class="font-semibold">ADD NEW COURSE</h1>
    <p class="text-primary-content mb-6">To get started choose the course title</p>
    </div>
   <form method="POST" action="" class="">
    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
      <div class="sm:col-span-4">
        <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Course Title</label>
        <div class="mt-2">
          <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
            <input type="text" name="username" id="username" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Type title here...">
          </div>
        </div>
      </div>

      <div class="col-span-full">
        <label for="about" class="block text-sm font-medium leading-6 text-gray-900">Course Description</label>
        <div class="mt-2">
          <textarea id="about" name="about" rows="3" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
        </div>
      </div>
          <div>
            <label for="price" class="block text-sm font-medium leading-6 text-gray-900">Price</label>
            <div class="relative mt-2 rounded-md shadow-sm">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <span class="text-gray-500 sm:text-sm">$</span>
              </div>
              <input type="text" name="price" id="price" class="block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="0.00">
              <div class="absolute inset-y-0 right-0 flex items-center">
                <label for="currency" class="sr-only">Currency</label>
                <select id="currency" name="currency" class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-gray-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">
                  <option>USD</option>
                  <option>ZWL</option>
                  <option>EUR</option>
                </select>
              </div>
            </div>
          </div>
          <div class="mt-4">
          <button class="btn btn-outline btn-accent mt-4">Add Courses</button>
          </div>
    </form>

{%endblock%}

flaskapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>MSU Courses | {% block title %}{% endblock title %}</title>
    <meta name="description" content="Simple landind page" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
    />
    <!--Daisy ui Link -->
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.6.0/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <!--Replace with your tailwind.css once created-->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
      rel="stylesheet"
    />
    <!-- Define your gradient here - use online tools to find a gradient matching your branding-->
    {% block styles %} {% endblock styles %}
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
  </head>
  <body
    class="leading-normal tracking-normal text-white gradient"
    style="font-family: 'Source Sans Pro', sans-serif"
  >
    <!--Navigation bar-->

    <!--/Navigation bar-->
    <div class="mt-6">
      {% include "navbar.html" %} {% with messages=
      get_flashed_messages(with_categories= True) %} {% if messages %} {% for
      category, message in messages %} {% if category == "success" %}
      <div
        x-data="{open: true}"
        x-init="setTimeout(()=>{open=false}, 2000)"
        x-show="open"
        class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 max-w-lg mx-auto mt-12"
        role="alert"
      >
        {{ message }}
      </div>
      {% elif category == "error" %}
      <div
        x-data="{open: true}"
        x-init="setTimeout(()=>{open=false}, 2000)"
        x-show="open"
        class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 max-w-lg mx-auto mt-12"
        role="alert"
      >
        {{ message }}
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %} {% block content %} {%
      endblock content %}
      <!--footer-->

      <!--/footer-->
    </div>
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

flaskapp/templates/course_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>Course Details</title>
</head>

<body>

    <div class="container mx-auto px-8 py-8">
        <div class="flex justify-between text-gray-500">
        <h1 class="text-2xl font-bold mb-8 mt-6">{{course.title}}</h1>
        <a href="{{url_for('creator.create_lesson')}}" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700 mt-6 mr-6"> + ADD LESSON</a>
            </div>

        <div class="mt-6">
            <a href="{{url_for('creator.creator_courses_list')}}" class="text-gray-600 font-semibold underline underline-offset-1">
                BACK TO MYCOURSES
            </a>
        <br>

        

        <div class="">
            <div class="bg-white rounded-lg border shadow-md my-4 p-4">
                <h2 class="text-lg font-bold mb-2">Lesson 1</h2>
                <p class="text-gray-600">Lesson description goes here.</p>
                <a href="{{ url_for('creator.course_details', course_id=course.id) }}" class="mt-2 text-blue-500 hover:underline">Edit</a>
            </div>

            <!-- Add more lesson cards as needed -->

        </div>
    </div>
</body>

</html>

flaskapp/templates/course_lessons.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lessons List</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
    <div class="container px-8 mx-auto mt-8">
       
        <div class="flex justify-between text-gray-500">
            <h1 class="text-2xl font-bold mb-8 mt-6">{{course.title}}</h1>
            <a href="{{url_for('creator.create_lesson')}}" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700 mt-6 mr-6"> + ADD LESSON</a>
                </div>

                <div class="mt-6">
                    <a href="{{url_for('creator.creator_courses_list')}}" class="text-gray-600 font-semibold underline underline-offset-1">
                        BACK TO MYCOURSES
                    </a>
                <br>

                {% for lesson in lessons %}
                <div class="bg-white border shadow rounded mt-4 p-4 mb-4">
                    <h2 class="text-lg font-bold mb-2">{{lesson.title}}</h2>
                    <p class="mb-2">{{lesson.summary}}</p>
                    <a href="{{url_for('creator.create_topic')}}" class="bg-blue-500 text-white rounded p-2">Create Topic</a>
                    <a href="{{url_for('creator.create_lesson', lesson_id=lesson.id)}}" class="bg-blue-500 text-white rounded p-2">Edit Lesson</a>
                </div>
                {% endfor %}
        
                
       
        
    </div>
</body>

</html>

flaskapp/templates/create_lesson.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <title>Create Lesson</title>
</head>

<body>
  <div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Create Lesson</h1>
    <form action="{{url_for('creator.create_lesson')}}" method="POST">
      <div class="mb-4">
        <label for="title" class="block text-gray-700 mb-2">Title</label>
        <input type="text" id="title" name="title" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
      </div>
      <div class="mb-4">
        <label for="summary" class="block text-gray-700 mb-2">Summary</label>
        <textarea id="summary" name="summary" rows="5" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required></textarea>
      </div>
      <div class="mb-4">
        <label for="objectives" class="block text-gray-700 mb-2">Objectives</label>
        <textarea id="objectives" name="objectives" rows="5" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required></textarea>
      </div>
      <div class="mb-4">
        <label for="duration" class="block text-gray-700 mb-2">Duration</label>
        <input type="text" id="duration" name="duration" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
      </div>
      <div>
        <button type="submit" class="bg-indigo-500 text-white px-4 py-2 rounded hover:bg-indigo-600">Create</button>
      </div>
    </form>
  </div>
</body>

</html>

flaskapp/templates/create_topic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <title>Create Topic</title>
</head>

<body>
  <div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Create Topic</h1>
    <form action="{{url_for('creator.create_topic')}}" method="POST" enctype="multipart/form-data">
      <div class="mb-4">
        <label for="title" class="block text-gray-700 mb-2">Title</label>
        <input type="text" id="title" name="title" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
      </div>
      
      <div class="mb-4">
        <label for="file" class="block text-gray-700 mb-2">Select File</label>
        <input type="file" id="file" name="content" class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-indigo-500" required>
      </div>

      <div>
        <button type="submit" class="bg-indigo-500 text-white px-4 py-2 rounded hover:bg-indigo-600">Upload</button>
      </div>
     
    </form>
  </div>
</body>

</html>

flaskapp/templates/creator-courses-list.html
{% extends "creatorlayout.html" %}
{% block title %} Lesson List{% endblock %}

{%block content%}

<div class="p-16 text-gray-500">
    <div class="flex justify-between text-gray-500">
        
    <h1 class="font-semibold">
        <div class="">
            {{user.email}}
            </div>
        MY COURSES
    </h1>
    <a href="{{url_for('creator.create_course')}}" class="btn btn-outline btn-accent"> + ADD NEW COURSE</a>
    </div>

    <div
 
class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Courses</h1>

    {% for course in courses %}
      <div class="bg-white border shadow rounded p-4 mb-4">
        <h2 class="text-lg font-bold mb-2">{{course.title}}</h2>
        <p class="mb-2">{{course.description}}</p>
        <a href="{{ url_for('creator.course_details', course_id=course.id) }}" class="bg-blue-500 text-white rounded p-2">Course Structure</a>
        <a href="{{ url_for('creator.update_course', course_id=course.id) }}" class="bg-blue-500 text-white rounded p-2">Edit Course</a>
      </div>
    {% endfor %}
  </div>



</div>
  
{%endblock%}

flaskapp/templates/creatorlayout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>MSU Courses | {% block title %}{% endblock title %}</title>
    <meta name="description" content="Simple landind page" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
    />
    <!--Daisy ui Link -->
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.6.0/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <!--Replace with your tailwind.css once created-->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
      rel="stylesheet"
    />
    <!-- Define your gradient here - use online tools to find a gradient matching your branding-->
    {% block styles %} {% endblock styles %}
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
  </head>
  <body
    class="leading-normal tracking-normal text-white gradient"
    style="font-family: 'Source Sans Pro', sans-serif"
  >
    <!--Navigation bar-->
    <div class="mb-6">{% include "navbar.html" %}</div>
    <!--/Navigation bar-->
   
    {%block content %}
    
    {%endblock%}

  </body>
</html>

flaskapp/templates/navbar.html
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div
    class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
  >
    <a
      href="{{url_for('views.home')}}"
      class="flex items-center space-x-3 rtl:space-x-reverse"
    >
      <span
        class="self-center text-2xl text-blue-700 font-semibold whitespace-nowrap dark:text-gray-500"
        >MSU <span class="text-yellow-700">Courses</span></span
      >
    </a>
    <button
      data-collapse-toggle="navbar-default"
      type="button"
      class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg
        class="w-5 h-5"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 17 14"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 1h15M1 7h15M1 13h15"
        />
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul
        class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
      >
        {% if user.is_authenticated %}
        <li>
          <a
            href="{{ url_for('auth.dashboard')}}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
            >Dashboard</a
          >
        </li>
        <li>
          <a
            href="{{ url_for('auth.logout')}}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
            >Logout</a
          >
        </li>
        {% else %}
        <li>
          <a
            href="{{url_for('views.home')}}"
            class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
            aria-current="page"
            >Home</a
          >
        </li>
        <li>
          <a
            href="{{ url_for('auth.register')}}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
            >Register</a
          >
        </li>
        <li>
          <a
            href="{{ url_for('auth.login')}}"
            class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
            >Login</a
          >
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>